### ISSUE TITLE
More needs to be said about books

### ISSUE THREAD

**Issue by shaneadams208** [keithwanda/Tech-Writing#5]
I think there are some useful books out there that will improve ones journey into tech writing.

**Comment by keithwanda** [comment]
Absolutely agreed. Any suggestions would be most welcome.

**Comment by keithwanda** [comment]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/120113293/208179106-b52321cc-ded3-4e8b-aebb-bbb47a6e14f2.png">

**Comment by keithwanda** [comment]
Maybe movie URL's could be good. I'm moving off the topic.

**Comment by keithwanda** [comment]
This fixes #5

**Comment by shaneadams208** [comment]
This fixes #5
